# WELCOME TO THE CONFIG
# - ADVANCE TO ADVANCE plugin, By Chanlanfan
# Please note:
#          - All values are INTEGERS (unless stated otherwise OR in quotations)!!
#          - ALL '_time' are in SECONDS (unless stated otherwise)!!
#          - For values where time should be subtracted from the player: USE A MINUS ('-') SYMBOL before the number (a negative integer). (unless stated otherwise)!!
#          ! For a clean copy of the config, visit the GitHub page, OR GO TO BOTTOM OF CONFIG.

#Basic seconds to minute conversion table: <seconds>
# min to sec  | Defaults:
# 1min : 60   | 900 : 15min
# 2min : 120  | 600 : 10min
# 3min : 180  | 300 : 5min

# THE DEFAULT TIME GIVEN TO A PLAYER WHEN JOINING FOR THE FIRST TIME
start_time: 900

# ACHIEVEMENT BONUS TIMES (When a player earns an achievement):
achievement_bonuses_enabled: 0

task_time: 300
goal_time: 600
challenge_time: 900

# PLAYER EVENTS (Non Achievement):
death_time: -300      # Time added to player on death (By all types)

#TIMER COLOURS: (Minimum time for colour, for example: 'green_time: 1800'; timer will turn yellow at 1800 seconds)
green_time: 1800
yellow_time: 600
gold_time: 300
red_time: 60


