name: AdvanceToAdvance
version: 0.1.4
main: org.chanlanfan.advancetoadvance.AdvanceToAdvance
api-version: '1.20'
commands:
  info:
    description: Overview of Plugin
    usage: /<command>
    aliases: ?i
  reloadata:
    description: Reloads the plugin (Basically the entire server, BUT DON'T FEAR!! it doesn't kick everyone, it does it uninterrupted)
    usage: /<command>
    aliases: ?rl
  test:
    description: Current testing
    usage: /<command>
    aliases: ?t
  settime:
    description: Set timer
    usage: /<command>
    aliases: ?st
  pause:
    description: pause timer
    usage: /<command>
    aliases: ?pt
